//! Embedded source inventory only: no native functions, types, Engine or VM.
macro_rules! sources {
    ($($name:literal),* $(,)?) => { &[$((concat!("std/", $name),
        include_str!(concat!("../modules/std/", $name, ".telora")))),*] };
}
pub const BUILTINS: &[(&str, &str)] = sources![
    "_codec",
    "_rt",
    "actor",
    "argv",
    "array",
    "blame",
    "codec",
    "dict",
    "dyn",
    "ees",
    "entry",
    "eq",
    "fmt",
    "hash",
    "json",
    "option",
    "path",
    "prelude",
    "regex",
    "result",
    "rt-types/exec",
    "string",
    "test",
    "toml",
    "type-desc",
    "type-property",
    "value",
    "yaml",
];

/// Language-defined names. Evidence for these belongs to the static type pass.
pub const INTRINSICS: &[&str] = &[
    "Type",
    "Dyn",
    "Never",
    "Unit",
    "Int",
    "Float",
    "String",
    "Bytes",
    "Bool",
    "PropertyTarget",
    "Array",
    "Dict",
    "TypeOf",
    "Unchecked",
    "Tuple",
    "Func",
    "Option",
    "Result",
    "FoldControl",
    "\0telora_pack_dyn",
    "\0telora_cast",
];
