// Owns the solved arena and compiler evidence. The caller retains the resolved
// HIR, including when solving or execution returns an error. Plans borrow source syntax;
// no field contains a heap, VM, runtime root or live inference solver.
struct SolvedModulePlan<'a> {
    types: TypeGraph,
    declared_types: BTreeMap<String, AnalysisTypeId>,
    binding_types: BTreeMap<String, AnalysisTypeId>,
    trait_ids: BTreeMap<String, crate::TraitId>,
    trait_implementations: Vec<TraitImplementation>,
    result_type: AnalysisTypeId,
    result_scheme: Option<TypeScheme>,
    definition_types: BTreeMap<HirDefinitionId, AnalysisTypeId>,
    definition_schemes: BTreeMap<HirDefinitionId, TypeScheme>,
    expression_types: BTreeMap<HirExpressionId, AnalysisTypeId>,
    module_interface: ModuleInterface,
    propagation_families: HashMap<crate::Location, PropagationFamily>,
    not_families: HashMap<crate::Location, NotFamily>,
    trait_member_evidence: HashMap<crate::Location, ResolvedEvidence>,
    generic_call_evidence: HashMap<crate::Location, Vec<ResolvedEvidence>>,
    interpolation_evidence: HashMap<crate::Location, ResolvedEvidence>,
    generic_evidence_parameters: HashMap<crate::Location, Vec<String>>,
    generic_dictionary_factories: HashMap<crate::Location, Vec<String>>,
    declared_value_owners: HashMap<crate::Location, ResolvedEvidence>,
    value_constructors: HashMap<crate::Location, ValueConstructor>,
    authored_names: HashSet<&'a str>,
    prelude_value_names: Vec<String>,
    declared_initializer_slots: HashMap<crate::Location, u32>,
    declaration_plans: Vec<DeclarationPlan<'a>>,
    tool_bindings_to_execute: Vec<SolvedToolBinding<'a>>,
    construction_checks: Vec<PreparedConstructionCheck>,
    property_plans: PreparedPropertyPlans,
    local_type_property_evidence: Vec<TypePropertyEvidence>,
    static_environment: HashMap<String, TypeDescriptor>,
    runtime_type_evidence: BTreeMap<String, TypeDescriptor>,
    owner_plans: Vec<DeclaredOwnerPlan>,
}
