[package]
name = "telora-wasm"
version.workspace = true
edition.workspace = true

[dependencies]
telora-core = { path = "../telora-core" }
wasm-encoder = "0.259"
wasmparser = "0.259"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
wasmi = "2"
